### PR TITLE
Cleanup and fixes crashes

### PR DESCRIPTION
**Pull request by rasm685p**
This isn't fully tested because I didn't have the time but it should fix the following issues:

1. https://github.com/rasm685p/Triangle-Wars/issues/4 "it's possible to crash the server by spamming trash data"
2. https://github.com/rasm685p/Triangle-Wars/issues/2 "Unnecessary for loop in connection.js"

This pull request will be merged when fully tested.

### CODE REVIEW

**Comment by rasm685p** [comment]
When I find time, I'll create some variables for some of the important data.

**Comment by BenStigsen** [comment]
I'm thinking this will be easier to prevent if there's put a limit on the amount of data sent (could cause data loss perhaps (unless the data is taken by most recent?)) or by adding a rate limit for the data sent.

**Comment by rasm685p** [comment]
@BenStigsen This pull request implements a rate limit and it's currently set to 30 requests every 5 second for every user. 

Here is a snippet of the most important code:
`function antispam(socket) {
    if (players[socket.id]) {
        players[socket.id].secure_data.requests -= 1;
        if (players[socket.id].secure_data.requests <= 0) {
            socket.disconnect();
        }
    }
}

function Player(ip) {
    this.data = {
        points: [],
        mouseclicks: [],
        color: [
            Math.floor(Math.random() * 255) + 1,
            Math.floor(Math.random() * 255) + 1,
            Math.floor(Math.random() * 255) + 1,
        ],
    };

setInterval(function () {
    for (var i in players) {
        players[i].secure_data.requests = 30;

        if (players[i].secure_data.disconnect_time > 0) {
            players[i].secure_data.disconnect_time -= 5;
            if (players[i].secure_data.disconnect_time == 0) {
                delete players[i];
                io.emit("disconnect", i);
            }
        }
    }
}, 5000);

    this.secure_data = {
        ip_address: ip,
        disconnect_time: -1, //Seconds until the player disconnects from the server
        requests: 30, // Max requests allowed every 5 second for every socket.id
    };`
As you can see, I'm just disconnecting them if their requests equals 0.

**Comment by BenStigsen** [comment]
Ah sorry, didn't see that. I'm still new to the mobile version of the app. Am I right to assume that you applied 30 seconds to their request before you disconnect them?

**Comment by rasm685p** [comment]
You'll have to go into details with that one. I'm a little confused about what you mean?

**Comment by rasm685p** [comment]
console.log(players); //Returns something undefined

I don't know why but right now it doesn't matter. This issue doesn't crash the server and it shouldn't break anything.

**Pull request merged**
